version: 2.1

jobs:
  # Hello World Job
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SonarQube Job
  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install SonarQube CLI
          command: |
                echo "Installing SonarQube CLI in home directory..."
                wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
                unzip sonar-scanner-cli-4.7.0.2747-linux.zip
                mv sonar-scanner-4.7.0.2747-linux ~/sonar-scanner
                export PATH=$PATH:~/sonar-scanner/bin
                echo 'export PATH=$PATH:~/sonar-scanner/bin' >> ~/.bashrc
                source ~/.bashrc
                echo "Verifying SonarQube CLI Installation..."
                ls -al ~/sonar-scanner/bin
                sonar-scanner --version
      - run:
          name: Verify `find` Installation
          command: find --version
      - run:
          name: Run `find` Command
          command: find .
      - run:
          name: Verify SonarQube Installation
          command: sonar-scanner --version
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run SonarQube Scanner
          command: |
            echo "Running SonarQube Scanner..."
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
